name: issue-workflow
on:
  issues:
    types: [opened]

jobs:
  issue-job:
    runㄴ-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world2
          echo hello github actions
